---
php_packages:
  - php7.4
  - php7.4-dev
  - php7.4-gd
  - php7.4-fpm
  - php7.4-mbstring
  - php7.4-xml
  - php7.4-xmlrpc
  - php7.4-mysql
  - php7.4-curl
  - php7.4-zip
  - php7.4-gd
  - php7.4-sqlite3
  - php7.4-soap
  - php7.4-intl
  - php7.4-odbc
  - php-xdebug
  - libapache2-mod-php7.4
