---
- name: Instalando MariaDB
  apt:
    name: mariadb-server
    state: latest

- name: Habilitando MariaDB na Inicialização
  service:
    name: mariadb
    enabled: yes

- name: Instalando dependências MariaDB
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ python_packages }}"

- name: Remove todos usuários anônimos
  community.mysql.mysql_user:
    name: ''
    state: absent
    login_user: root
    login_password: { mysql_root_password }
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove banco de dados de teste
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: { mysql_root_password }
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Copiando arquivo de senha do MariaDB
  ansible.builtin.copy:
    src: ".my.cnf"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: '0644'