---
- hosts: banco
  become: true
  roles:
    - update
    - tools
    - mariadb-install
    - mariadb-config
    #- ufw-db

- hosts: web
  become: true
  roles:
    - update
    - tools
    - apache
    - php7.4
    - apache-config
    - wordpress
    #- ufw-web
